---
version: 2
jobs:
  build:
    steps:
      - run: curl https://mozilla.cloud.looker.com/webhooks/projects/spoke-default/deploy
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
            tags:
              only: /.*/
